ALTER TABLE PROJEKTY
ADD CONSTRAINT PK_PROJEKTU PRIMARY KEY(ID_PROJEKTU);

ALTER TABLE PROJEKTY
ADD CONSTRAINT UK_PROJEKTY UNIQUE(OPIS_PROJEKTU);

ALTER TABLE PROJEKTY
MODIFY OPIS_PROJEKTU NOT NULL;

ALTER TABLE PROJEKTY
ADD CONSTRAINT DATA_X CHECK(DATA_ZAKONCZENIA>DATA_ROZPOCZECIA);

ALTER TABLE PROJEKTY
ADD CONSTRAINT FUND_DOD CHECK(FUNDUSZ>0);

SELECT c.constraint_name, c.CONSTRAINT_type, c.SEARCH_CONDITION, cc.column_name
FROM user_constraints c join user_cons_columns cc
on cc.constraint_name=cc.constraint_name
WHERE c.table_name = 'PROJEKTY'
order by c.constraint_name;

INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Indeksy bitmapowe',DATE '2015-04-12', DATE '2016-09-30', 40000);

CREATE TABLE PRZYDZIALY(
 ID_PROJEKTU NUMBER(4) NOT NULL CONSTRAINT FK_PRZYDZIALY_01 REFERENCES PROJEKTY(ID_PROJEKTU),
 NR_PRACOWNIKA NUMBER(6) NOT NULL CONSTRAINT FK_PRZYDZIALY_02 REFERENCES PRACOWNICY(ID_PRAC),
 OD DATE DEFAULT CURRENT_DATE,
 DO DATE , CONSTRAINT CHK_PRZYDZIALY_DATY CHECK(DO>OD),
 STAWKA NUMBER(7,2) CONSTRAINT CHK_PRZYDZIALY_STAWKA CHECK(STAWKA>0),
 ROLA VARCHAR(20) CONSTRAINT CHK_PRZYDEZIALY_ROLA CHECK(ROLA IN ('KIERUJĄCY', 'ANALITYK', 'PROGRAMISTA'),
 CONSTRAINT PK_PRZYDZIALY PRIMARY KEY(ID_PROJEKTU)));
 